### ISSUE TITLE
支持微信和支付宝扫码支付？

### ISSUE THREAD

**Issue by hustKiwi** [PingPlusPlus/pingpp-html5#10]
你好，我想在网页端使用 `pingpp` 。看文档的[FAQ](https://pingxx.com/faq/)上说：
>
Ping++ 还支持微信和支付宝扫码支付

但是我看了下源码，渠道中似乎没有覆盖扫码支付吧：
https://github.com/PingPlusPlus/pingpp-html5/blob/master/src/pingpp_pay.js#L17-25

请问应该如何实现？

**Comment by hustKiwi** [comment]
补充一下，从[这份API文档](https://pingxx.com/document/api?node.js#api-charges)看，咱们支持的付费渠道还是挺多的：
>
alipay: 支付宝手机支付
alipay_wap：支付宝手机网页支付
alipay_qr：支付宝扫码支付
apple_pay：Apple Pay
bfb：百度钱包移动快捷支付
bfb_wap：百度钱包手机网页支付
upacp:银联全渠道支付（2015 年 1 月 1 日后的银联新商户使用。若有疑问，请与 Ping++ 或者相关的收单行联系）
upacp_wap：银联全渠道手机网页支付（2015 年 1 月 1 日后的银联新商户使用。若有疑问，请与 Ping++ 或者相关的收单行联系）
upmp：银联手机支付（限个人工作室和 2014 年之前的银联老客户使用。若有疑问，请与 Ping++ 或者相关的收单行联系）
upmp_wap：银联手机网页支付（限个人工作室和 2014 年之前的银联老客户使用。若有疑问，请与 Ping++ 或者相关的收单行联系）
wx：微信支付
wx_pub：微信公众账号支付
wx_pub_qr：微信公众账号扫码支付
yeepay_wap：易宝手机网页支付
jdpay_wap：京东手机网页支付

但这里提供的 `client sdk` 似乎支持的比较少。如果选择了 alipay_qr 渠道，会触发下面的检验逻辑，被认为是非法渠道：
https://github.com/PingPlusPlus/pingpp-html5/blob/master/src/pingpp_pay.js#L81-84

**Comment by lumixiliu** [comment]
你仔细看一下关于渠道那个文档里面对于扫码的介绍。扫码不需要客户端SDK的支持。只需要服务器端调用charge接口，拿到charge对象后从credential字段里取出二维码链接去生成二维码即可。

发自 lumixiliu

**Comment by samurai00** [comment]
pingpp-html5 支持的是 WAP 渠道以及微信公众号支付。
扫码支付不需要 Client SDK。
其他渠道需要使用 [pingpp-ios](https://github.com/PingPlusPlus/pingpp-ios) 或者 [pingpp-android](https://github.com/PingPlusPlus/pingpp-android)。

**Comment by hustKiwi** [comment]
@lumixiliu @samurai00  不好意思，我当时直接看的API文档，没有发现对渠道的进一步说明。经你提醒，已经在在 guidance 中找到对扫码操作的说明。不过还要请教一下，扫码这个渠道如何本地开发测试，一定需要签约后使用真实支付？因为在使用测试key时，credential中给出的也是正式环境的扫描链接吧，例如这样的：https://qr.alipay.com/4C80iPzPerPGKOq1eP

**Comment by samurai00** [comment]
@hustKiwi 测试模式这部分正在改进。目前还不支持扫码渠道的模拟付款。

**Comment by hustKiwi** [comment]
@samurai00 OK，建议对于扫码，使用测试key时，后端返回的 credential 地址就是 pingpp 的测试交易的地址。对开发者而言，正式模式和测试模式的流程应该一致和透明，不需要对代码做任何修改才对。

**Comment by samurai00** [comment]
是的，我们是打算这么做的。
