### ISSUE TITLE
求完整版本的 https://one.pingxx.com/lib/pingpp_one.js

### ISSUE THREAD

**Issue by yreme** [PingPlusPlus/pingpp-html5#18]
我在`ruby on rails`能够成功使用 `https://one.pingxx.com/lib/pingpp_one.js ` !

 现在的问题是,  我想 html5的离线特性,把pingpp_one.js缓存到本地,   优化用户体验. 但 离线版本的`pingpp_one.js` 会抓取` https://one.pingxx.com/lib/sea.js` 并 报出错误
```ruby
GET https://one.pingxx.com/lib/sea.js net::ERR_FAILED
````
其中 `https://one.pingxx.com/lib/pingpp_one.js` 的部分代码为:
```javascript

    var one_url='https://one.pingxx.com/one_html5_v2/index.js';
    var sea_url='https://one.pingxx.com/lib/sea.js';
    var pingpp_one=function(){};

    window.pingpp_one=new pingpp_one();

    var e=document.createEvent('Event');
    e.initEvent('pingpp_one_ready',true,true);

    var use=function(){
        seajs.use(one_url,function(index){
            var t=index('./init');
            var s=index('./success');

            pingpp_one.prototype.init=function(opt,callback){
                t.init(opt,callback);
            };

            pingpp_one.prototype.success=function(callback,continueCallback){
                s.init(callback,continueCallback);
            };

            pingpp_one.prototype.resume=function(){
                t.resume();
            };

            document.dispatchEvent(e);
        });
    };
```
我猜想这个就是问题所在, 因此能否麻烦您给我一个合并以下三个js文件的大js吗
+  https://one.pingxx.com/lib/sea.js
+ https://one.pingxx.com/one_html5_v2/index.js
+ https://one.pingxx.com/lib/pingpp_one.js

谢谢!

**Comment by samurai00** [comment]
你直接把这三个文件下载下来就可以了。

**Comment by yreme** [comment]
在 rails 正常环境可以使用, 但离线缓存的情况, 就会出现 上面的问题和 `https://one.pingxx.com/one_html5_v2/index.js net::ERR_FAILED`

**Comment by samurai00** [comment]
你把 https://one.pingxx.com/lib/pingpp_one.js 这里的两个 URL 也改成你自己的 URL。

**Comment by yreme** [comment]
现在不是改网址的问题, 这个网址实际上可访问, 换成其他网址,仍然会出这个问题!

您有办法把**三个文件合并成一个文件**吗? 不是简单的把三个文件拷贝到一起!!!

**Comment by samurai00** [comment]
如果是简单的把三个文件拷贝在一起，你也可以合并啊...
你告诉我是怎么加载 js 文件的，我给你解决方法。

**Comment by yreme** [comment]
稍等.. 我马上弄个ruby rails的测试demo 给您

**Comment by yanglang** [comment]
我也碰到了这个问题，请问有解决方案吗？
