### ISSUE TITLE
PC端的微信扫码支付(channel: "wx_pub_qr")是怎么个流程 ...

### ISSUE THREAD

**Issue by xyhp915** [PingPlusPlus/pingpp-html5#20]
求指点迷津🐵

**Comment by xyhp915** [comment]
Ping @samurai00

**Comment by samurai00** [comment]
看一下这个：https://help.pingxx.com/article/125867

**Comment by xyhp915** [comment]
@samurai00 好的谢谢，已阅，之前搜了一下帮助文档，么搜到我的错误。。。
还有个问题，就是回调地址：
![d435ce41-396d-4621-8f0a-a60cdf217c4c](https://cloud.githubusercontent.com/assets/1779837/13560846/8cfb4d2c-e45f-11e5-8505-c3eb02e25761.png)
 
这个需要设置吗？或者Ping++那边通过主动方式获取状态然后回调设置的webhook ？

**Comment by samurai00** [comment]
这个不用设置。
我们这边会通过接口处理的。

**Comment by xyhp915** [comment]
@samurai00 Thanks 👍
