### ISSUE TITLE
微信和支付宝调用客户端

### ISSUE THREAD

**Issue by fa-ge** [PingPlusPlus/pingpp-html5#28]
支付宝支付不能调起支付宝客户端。微信支付也想在非微信内置浏览器中调起微信客户端进行支付，能做到吗？

**Comment by samurai00** [comment]
支付宝网页支付只能调网页的。微信的话，目前不支持浏览器调用客户端，微信本身对商户也有限制，不给一般的商户开发 wap 接口。

**Comment by fa-ge** [comment]
http://m.iqiyi.com/pay.html?plg_nld=1&plg_vkey=1&plg_auth=1&fc=a07f43eca43cb5c8&platform=97ae2982356f69d8&plg_dev=1&plg_nld=1&plg_uin=1&serviceCode=lyksc7aq36aedndk&plg_usr=1&qy_fr=H5-VIP-0201&pid=a0226bd958843452
我不是很清楚爱奇艺是怎么做到支付宝调起客户端支付的。

**Comment by samurai00** [comment]
这个你可以去支付宝那边人工申请开通这种功能，不能直接通过代码或者接口开启。

**Comment by fa-ge** [comment]
好的。。谢谢
