### ISSUE TITLE
upmp_wap回调地址跳转错误

### ISSUE THREAD

**Issue by henter** [PingPlusPlus/pingpp-html5#6]
应跳转地址： xxx.com/pay/upmp_wap/result
实际跳转地址： xxx.com/pay/upmp_wap/result0

**Comment by lumixiliu** [comment]
upmp_wap 渠道的 result_url 是 Client 支付结果通知 url。 该 url 主要用于支付控件的支付完成或者失败后通知浏览器跳转的地址。该 url 需要接受一个参数，由控件返回，返回参数为：

0 - 支付成功时返回
1 - 支付失败时返回
-1 - 支付取消时返回
示例如下（其中蓝色部分为你填写的 result_url、 红色的数字为控件追加）：

http://example.com/example?argName=0
http://example.com/example?argName=1
http://example.com/example?argName=-1
支付成功跳转到 http://example.com/result.php?code=0，
失败则跳转到 http://example.com/result.php?code=1，
取消则跳转到 http://example.com/result.php?code=-1。

你应该是extra 参数里面的 result_url 填写的不对。具体可以参考 https://pingxx.com/guidance/config

**Comment by henter** [comment]
@lumixiliu 好的谢谢
