### ISSUE TITLE
请支持 bower 下载

### ISSUE THREAD

**Issue by fundon** [PingPlusPlus/pingpp-html5#7]
类似 `bower install pingpp`

**Comment by samurai00** [comment]
我们这边会考虑支持的，谢谢。

**Comment by fundon** [comment]
`npm install pingpp-client ` 也行，叫开发者去单独去下个文件略蛋疼

**Comment by hustKiwi** [comment]
@samurai00 https://github.com/PingPlusPlus/pingpp-html5/pull/9
